baseurl = "http://www.example.com" # Hostname (and path) to the root.
title = "Vatsalya Tandon" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Vatsalya Tandon" # Author's name.
    info = "Junior Undergraduate, IIT Kanpur" # Author's job title or info.
    description = "Vatsalya's personal website" # Site description.
    keywords = "blog, data science, consulting, personal" # Site keywords.
    avatarurl = "images/profile.jpg" # Contain the path of the optional avatar in the static folder.

    footercontent = "You miss 100% of the shots you don't take - Wayne Gretzky - Michael Scott" # Add footer content
   
    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/vatsalyatandon/"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/vatsalyatandon/"
[[params.social]]
    name = "Facebook"
    weight = 3
    url = "https://facebook.com/mynameisvt/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
[[menu.main]]
    name="Experience"
    weight = 3
    url = "experience"
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "contact"
